[project]
name = "liveflowai"
version = "0.1.3"
description = "A Python-based audio analysis toolkit for real-time tempo and chord detection from music files and live microphone input."
readme = "README.md"
authors = [
    { name = "Hioe Gregorius Owen", email = "bloggerzz231@gmail.com" },
    { name = "Petrus Aria Prakoso Widarto", email = "ariaprakoso@proton.me" }
]
requires-python = ">=3.10, <3.11"
dependencies = [
    "librosa>=0.10.0",
    "numpy>=1.22,<2.0",
    "matplotlib>=3.10.9",
]

[project.optional-dependencies]
live-audio = [
    "sounddevice>=0.5.5",
]
iem = [
    "pyttsx3>=2.99",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.scripts]
liveflowai = "liveflowai.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
