[project]
name = "liveflowai"
version = "0.1.0"
description = "LPB 2026 Banten type shi. Research and stuff."
readme = "README.md"
authors = [
    { name = "bloggerzz231-jpg", email = "bloggerzz231@gmail.com" },
    { name = "Arialize", email = "ariaprks@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "librosa>=0.10.0",
    "numpy<2.0",
    "scipy>=1.13.0",
    "scikit-learn>=1.4.0",
    "harmonyscope>=1.0.0",
    "soundfile>=0.12.0",
    "audioread>=3.0.0",
    "resampy>=0.4.0",
    "cython>=0.25",
    "mido>=1.2.6",
    "basic-pitch>=0.4.0",
    "matplotlib>=3.10.9",
    "ffmpeg-python>=0.2.0",
    "pathlib>=1.0.1",
    "typing>=3.10.0.0",
    "pyaudio>=0.2.14",
    "pytest>=9.1.1",
]

[project.scripts]
liveflowai = "liveflowai:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
