[project]
name = "liveflowai"
version = "0.1.0"
description = "A Python-based audio analysis toolkit for real-time tempo and chord detection from music files and live microphone input."
readme = "README.md"
authors = [
    { name = "Hioe Gregorius Owen", email = "bloggerzz231@gmail.com" },
    { name = "Petrus Aria Prakoso Widarto", email = "ariaprakoso@proton.me" }
]
requires-python = ">=3.10"
dependencies = [
    "librosa>=0.10.0",
    "numpy<2.0",
    "scipy>=1.13.0",
    "scikit-learn>=1.4.0",
    "harmonyscope>=1.0.0",
    "soundfile>=0.12.0",
    "audioread>=3.0.0",
    "resampy>=0.4.0",
    "cython>=0.25",
    "mido>=1.2.6",
    "basic-pitch>=0.4.0",
    "matplotlib>=3.10.9",
    "ffmpeg-python>=0.2.0",
    "pathlib>=1.0.1",
    "typing>=3.10.0.0",
    "pyaudio>=0.2.14",
    "pytest>=9.1.1",
    "sounddevice>=0.5.5",
    "pyttsx3>=2.99",
]

[project.scripts]
liveflowai = "liveflowai.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
